### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by lilialnas** [Alessandro018/Eis-aQuestao#26]
- [ ] Concluir a modelagem do banco
- [ ] Entender o mecanismo de Seed do Laravel
- [ ] Popular tabelas com Seed (Professor, Curso, Disciplina, Estudante, Período letivo e seus relacionamentos) 
- [ ] Login de professor (levando para uma página com os períodos letivos onde ele tem disciplina cadastrada)
