### ISSUE TITLE
Sprint 4 

### ISSUE THREAD

**Issue by lilialnas** [Alessandro018/Eis-aQuestao#33]
- [x] Criar migrations para as tabelas de relacionamento (Sprint 3) 
- [x] Povoar tabelas de relacionamento (Sprint 3) 
- [ ] Login de professor (levando para uma página com os períodos letivos onde ele tem disciplina cadastrada) 
- [x] CRUD de questões 
- [ ] CRUD de alternativas
