### ISSUE TITLE
Sprint 13

### ISSUE THREAD

**Issue by lilialnas** [Alessandro018/Eis-aQuestao#96]
- [ ] - Corrigir bugs funcionais da funcionalidade de questões
- [ ] - Corrigir bugs funcionais da funcionalidade de provas
- [ ] - Gerar prova em PDF por turma
- [ ] - Padronizar layout do sistema ( cor de botão, organização dos elementos padrão em toda tela).
- [ ] - Funcionalidade de importar turma deve ter mais clareza e prevenir o usuário de importar arquivos incorretos ou com o formato de recebimento errado.
